<x-app-layout>
    <x-slot name="breadcrumbParent">{{ $assignedView ? __('Assigned Sections') : __('Sections') }}</x-slot><x-slot name="breadcrumbParentUrl">{{ route('sections.index') }}</x-slot><x-slot name="breadcrumb">{{ $section->name }}</x-slot>
    <x-slot name="header"><div class="d-flex flex-column flex-sm-row align-items-sm-center justify-content-between gap-3"><div><div class="d-flex flex-wrap align-items-center gap-2 mb-1"><h1 class="h3 mb-0">{{ __('Section :name', ['name' => $section->name]) }}</h1>@if ($section->trashed())<span class="badge text-bg-dark">{{ __('Archived') }}</span>@else<span class="badge {{ $section->status === 'active' ? 'text-bg-success' : 'text-bg-secondary' }}">{{ ucfirst($section->status) }}</span>@endif</div><p class="text-body-secondary mb-0">{{ $section->schoolClass->name }} ({{ $section->schoolClass->code }})</p></div>@can('update', $section)<a class="btn btn-outline-primary align-self-start" href="{{ route('sections.edit', $section) }}"><i class="bi bi-pencil me-1" aria-hidden="true"></i>{{ __('Edit') }}</a>@endcan</div></x-slot>
    @include('academic.partials.navigation')
    @if (session('status'))<div class="alert alert-success" role="status">{{ session('status') }}</div>@endif
    @if ($errors->any())<div class="alert alert-danger" role="alert">{{ $errors->first() }}</div>@endif
    @if ($section->trashed())<div class="alert alert-secondary"><i class="bi bi-archive me-2" aria-hidden="true"></i>{{ __('This retained Section is archived. Restore it before activation or editing.') }}</div>@endif
    <div class="card border-0 shadow-sm"><div class="card-body"><h2 class="h5 mb-3">{{ __('Section Details') }}</h2><dl class="row mb-0"><dt class="col-sm-4">{{ __('Class') }}</dt><dd class="col-sm-8">{{ $section->schoolClass->name }}</dd><dt class="col-sm-4">{{ __('Section') }}</dt><dd class="col-sm-8">{{ $section->name }}</dd><dt class="col-sm-4">{{ __('Class Teacher') }}</dt><dd class="col-sm-8">{{ $section->teacher?->user?->name ?: __('Not assigned') }}</dd><dt class="col-sm-4">{{ __('Capacity') }}</dt><dd class="col-sm-8">{{ $section->capacity ?: '—' }}</dd>@if (auth()->user()->isSuperAdmin())<dt class="col-sm-4">{{ __('School') }}</dt><dd class="col-sm-8">{{ $section->school->name }}</dd>@endif<dt class="col-sm-4">{{ __('State') }}</dt><dd class="col-sm-8 mb-0">{{ $section->trashed() ? __('Archived') : ucfirst($section->status) }}</dd></dl></div></div>
    <div class="d-flex flex-wrap gap-2 mt-4">@can('activate', $section)<button class="btn btn-outline-success" type="button" data-bs-toggle="modal" data-bs-target="#activateSectionModal"><i class="bi bi-check-circle me-1" aria-hidden="true"></i>{{ __('Activate') }}</button>@endcan @can('deactivate', $section)<button class="btn btn-outline-warning" type="button" data-bs-toggle="modal" data-bs-target="#deactivateSectionModal"><i class="bi bi-slash-circle me-1" aria-hidden="true"></i>{{ __('Deactivate') }}</button>@endcan @can('archive', $section)<button class="btn btn-outline-danger" type="button" data-bs-toggle="modal" data-bs-target="#archiveSectionModal"><i class="bi bi-archive me-1" aria-hidden="true"></i>{{ __('Archive') }}</button>@endcan @can('restore', $section)<button class="btn btn-outline-primary" type="button" data-bs-toggle="modal" data-bs-target="#restoreSectionModal"><i class="bi bi-arrow-counterclockwise me-1" aria-hidden="true"></i>{{ __('Restore') }}</button>@endcan</div>
    @can('activate', $section)@include('academic.partials.confirmation-modal', ['modalId' => 'activateSectionModal', 'title' => __('Activate Section'), 'message' => __('The parent Class and assigned Teacher Profile must remain active.'), 'action' => route('sections.activate', $section), 'buttonLabel' => __('Activate'), 'buttonClass' => 'btn-success'])@endcan
    @can('deactivate', $section)@include('academic.partials.confirmation-modal', ['modalId' => 'deactivateSectionModal', 'title' => __('Deactivate Section'), 'message' => __('This preserves the Section and its assignment for later reactivation.'), 'action' => route('sections.deactivate', $section), 'buttonLabel' => __('Deactivate'), 'buttonClass' => 'btn-warning'])@endcan
    @can('archive', $section)@include('academic.partials.confirmation-modal', ['modalId' => 'archiveSectionModal', 'title' => __('Archive Section'), 'message' => __('This preserves the Section identity and reserves its name in the Class.'), 'action' => route('sections.archive', $section), 'buttonLabel' => __('Archive'), 'buttonClass' => 'btn-danger'])@endcan
    @can('restore', $section)@include('academic.partials.confirmation-modal', ['modalId' => 'restoreSectionModal', 'title' => __('Restore Section'), 'message' => __('The original Section returns inactive after relationship validation.'), 'action' => route('sections.restore', $section), 'buttonLabel' => __('Restore as Inactive'), 'buttonClass' => 'btn-primary'])@endcan
</x-app-layout>
