<x-app-layout>
    <x-slot name="header"><div class="d-flex flex-column flex-sm-row align-items-sm-center justify-content-between gap-3"><div><h1 class="h3 mb-1">{{ $assignedView ? __('Assigned Subjects') : __('Subjects') }}</h1><p class="text-body-secondary mb-0">{{ $assignedView ? __('View your active Subject assignments.') : __('Manage Subjects, types, Teacher assignments, and lifecycle state.') }}</p></div>@can('create', \App\Models\Subject::class)<a class="btn btn-primary align-self-start" href="{{ route('subjects.create') }}"><i class="bi bi-plus-lg me-1" aria-hidden="true"></i>{{ __('New Subject') }}</a>@endcan</div></x-slot>
    @include('academic.partials.navigation')
    @if (session('status'))<div class="alert alert-success" role="status">{{ session('status') }}</div>@endif
    <form class="row g-2 align-items-end mb-4" method="GET" action="{{ route('subjects.index') }}">
        <div class="{{ $assignedView ? 'col-md-8' : 'col-md-5' }}"><label class="form-label" for="search">{{ __('Search') }}</label><input id="search" name="search" type="search" class="form-control" value="{{ request('search') }}" maxlength="150" placeholder="{{ __('Subject name or code') }}"></div>
        <div class="col-sm-6 col-md-3"><label class="form-label" for="subject_type">{{ __('Subject Type') }}</label><select id="subject_type" name="subject_type" class="form-select"><option value="">{{ __('All types') }}</option><option value="theory" @selected(request('subject_type') === 'theory')>{{ __('Theory') }}</option><option value="practical" @selected(request('subject_type') === 'practical')>{{ __('Practical') }}</option><option value="optional" @selected(request('subject_type') === 'optional')>{{ __('Optional') }}</option></select></div>
        @unless ($assignedView)<div class="col-sm-6 col-md-2"><label class="form-label" for="state">{{ __('State') }}</label><select id="state" name="state" class="form-select"><option value="">{{ __('All states') }}</option><option value="active" @selected(request('state') === 'active')>{{ __('Active') }}</option><option value="inactive" @selected(request('state') === 'inactive')>{{ __('Inactive') }}</option><option value="archived" @selected(request('state') === 'archived')>{{ __('Archived') }}</option></select></div>@endunless
        <div class="col-sm-12 col-md-2 d-flex gap-2"><button class="btn btn-outline-primary" type="submit" title="{{ __('Apply filters') }}"><i class="bi bi-funnel" aria-hidden="true"></i><span class="visually-hidden">{{ __('Apply filters') }}</span></button><a class="btn btn-outline-secondary" href="{{ route('subjects.index') }}" title="{{ __('Clear filters') }}"><i class="bi bi-x-lg" aria-hidden="true"></i><span class="visually-hidden">{{ __('Clear filters') }}</span></a></div>
    </form>
    <div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table align-middle mb-0"><thead class="table-light"><tr><th scope="col">{{ __('Subject') }}</th><th scope="col">{{ __('Class') }}</th>@if (auth()->user()->isSuperAdmin())<th scope="col">{{ __('School') }}</th>@endif<th scope="col">{{ __('Type') }}</th><th scope="col">{{ __('Teacher') }}</th><th scope="col">{{ __('State') }}</th><th scope="col" class="text-end">{{ __('Actions') }}</th></tr></thead><tbody>
        @forelse ($subjects as $subject)<tr><td><div class="fw-semibold">{{ $subject->name }}</div><div class="small text-body-secondary">{{ $subject->code }}</div></td><td>{{ $subject->schoolClass->name }}</td>@if (auth()->user()->isSuperAdmin())<td>{{ $subject->school->name }}</td>@endif<td>{{ ucfirst($subject->subject_type) }}</td><td>{{ $subject->teacher?->user?->name ?: '—' }}</td><td>@if ($subject->trashed())<span class="badge text-bg-dark">{{ __('Archived') }}</span>@else<span class="badge {{ $subject->status === 'active' ? 'text-bg-success' : 'text-bg-secondary' }}">{{ ucfirst($subject->status) }}</span>@endif</td><td class="text-end text-nowrap"><a class="btn btn-sm btn-outline-secondary" href="{{ route('subjects.show', $subject) }}"><i class="bi bi-eye me-1" aria-hidden="true"></i>{{ __('View') }}</a>@can('update', $subject) <a class="btn btn-sm btn-outline-primary" href="{{ route('subjects.edit', $subject) }}"><i class="bi bi-pencil me-1" aria-hidden="true"></i>{{ __('Edit') }}</a>@endcan</td></tr>
        @empty<tr><td colspan="{{ auth()->user()->isSuperAdmin() ? 7 : 6 }}" class="text-center text-body-secondary py-4">{{ $assignedView ? __('No active Subjects are currently assigned to you.') : __('No Subjects match these filters.') }}</td></tr>@endforelse
    </tbody></table></div></div><div class="mt-3">{{ $subjects->links() }}</div>
</x-app-layout>
