<x-app-layout>
    <x-slot name="breadcrumbParent">{{ $assignedView ? __('Assigned Subjects') : __('Subjects') }}</x-slot><x-slot name="breadcrumbParentUrl">{{ route('subjects.index') }}</x-slot><x-slot name="breadcrumb">{{ $subject->name }}</x-slot>
    <x-slot name="header"><div class="d-flex flex-column flex-sm-row align-items-sm-center justify-content-between gap-3"><div><div class="d-flex flex-wrap align-items-center gap-2 mb-1"><h1 class="h3 mb-0">{{ $subject->name }}</h1>@if ($subject->trashed())<span class="badge text-bg-dark">{{ __('Archived') }}</span>@else<span class="badge {{ $subject->status === 'active' ? 'text-bg-success' : 'text-bg-secondary' }}">{{ ucfirst($subject->status) }}</span>@endif</div><p class="text-body-secondary mb-0">{{ $subject->code }} · {{ $subject->schoolClass->name }}</p></div>@can('update', $subject)<a class="btn btn-outline-primary align-self-start" href="{{ route('subjects.edit', $subject) }}"><i class="bi bi-pencil me-1" aria-hidden="true"></i>{{ __('Edit') }}</a>@endcan</div></x-slot>
    @include('academic.partials.navigation')
    @if (session('status'))<div class="alert alert-success" role="status">{{ session('status') }}</div>@endif
    @if ($errors->any())<div class="alert alert-danger" role="alert">{{ $errors->first() }}</div>@endif
    @if ($subject->trashed())<div class="alert alert-secondary"><i class="bi bi-archive me-2" aria-hidden="true"></i>{{ __('This retained Subject is archived. Restore it before activation or editing.') }}</div>@endif
    <div class="card border-0 shadow-sm"><div class="card-body"><h2 class="h5 mb-3">{{ __('Subject Details') }}</h2><dl class="row mb-0"><dt class="col-sm-4">{{ __('Class') }}</dt><dd class="col-sm-8">{{ $subject->schoolClass->name }}</dd><dt class="col-sm-4">{{ __('Name') }}</dt><dd class="col-sm-8">{{ $subject->name }}</dd><dt class="col-sm-4">{{ __('Code') }}</dt><dd class="col-sm-8">{{ $subject->code }}</dd><dt class="col-sm-4">{{ __('Type') }}</dt><dd class="col-sm-8">{{ ucfirst($subject->subject_type) }}</dd><dt class="col-sm-4">{{ __('Assigned Teacher') }}</dt><dd class="col-sm-8">{{ $subject->teacher?->user?->name ?: __('Not assigned') }}</dd>@if (auth()->user()->isSuperAdmin())<dt class="col-sm-4">{{ __('School') }}</dt><dd class="col-sm-8">{{ $subject->school->name }}</dd>@endif<dt class="col-sm-4">{{ __('State') }}</dt><dd class="col-sm-8 mb-0">{{ $subject->trashed() ? __('Archived') : ucfirst($subject->status) }}</dd></dl></div></div>
    <div class="d-flex flex-wrap gap-2 mt-4">@can('activate', $subject)<button class="btn btn-outline-success" type="button" data-bs-toggle="modal" data-bs-target="#activateSubjectModal"><i class="bi bi-check-circle me-1" aria-hidden="true"></i>{{ __('Activate') }}</button>@endcan @can('deactivate', $subject)<button class="btn btn-outline-warning" type="button" data-bs-toggle="modal" data-bs-target="#deactivateSubjectModal"><i class="bi bi-slash-circle me-1" aria-hidden="true"></i>{{ __('Deactivate') }}</button>@endcan @can('archive', $subject)<button class="btn btn-outline-danger" type="button" data-bs-toggle="modal" data-bs-target="#archiveSubjectModal"><i class="bi bi-archive me-1" aria-hidden="true"></i>{{ __('Archive') }}</button>@endcan @can('restore', $subject)<button class="btn btn-outline-primary" type="button" data-bs-toggle="modal" data-bs-target="#restoreSubjectModal"><i class="bi bi-arrow-counterclockwise me-1" aria-hidden="true"></i>{{ __('Restore') }}</button>@endcan</div>
    @can('activate', $subject)@include('academic.partials.confirmation-modal', ['modalId' => 'activateSubjectModal', 'title' => __('Activate Subject'), 'message' => __('The parent Class and assigned Teacher Profile must remain active.'), 'action' => route('subjects.activate', $subject), 'buttonLabel' => __('Activate'), 'buttonClass' => 'btn-success'])@endcan
    @can('deactivate', $subject)@include('academic.partials.confirmation-modal', ['modalId' => 'deactivateSubjectModal', 'title' => __('Deactivate Subject'), 'message' => __('This preserves the Subject and its assignment for later reactivation.'), 'action' => route('subjects.deactivate', $subject), 'buttonLabel' => __('Deactivate'), 'buttonClass' => 'btn-warning'])@endcan
    @can('archive', $subject)@include('academic.partials.confirmation-modal', ['modalId' => 'archiveSubjectModal', 'title' => __('Archive Subject'), 'message' => __('This preserves the Subject identity and reserves its code in the Class.'), 'action' => route('subjects.archive', $subject), 'buttonLabel' => __('Archive'), 'buttonClass' => 'btn-danger'])@endcan
    @can('restore', $subject)@include('academic.partials.confirmation-modal', ['modalId' => 'restoreSubjectModal', 'title' => __('Restore Subject'), 'message' => __('The original Subject returns inactive after relationship validation.'), 'action' => route('subjects.restore', $subject), 'buttonLabel' => __('Restore as Inactive'), 'buttonClass' => 'btn-primary'])@endcan
</x-app-layout>
