<?php

$roles = [
    'super_admin' => [
        'name' => 'Super Admin',
        'description' => 'Platform administrator with authorized system-wide access.',
    ],
    'school_admin' => [
        'name' => 'School Admin',
        'description' => 'School administrator with access to own school operations.',
    ],
    'teacher' => [
        'name' => 'Teacher',
        'description' => 'Teacher with access to assigned academic workflows.',
    ],
    'accountant' => [
        'name' => 'Accountant',
        'description' => 'Accountant with access to fee and financial workflows.',
    ],
];

$permissions = [
    'profile.view' => ['name' => 'Profile View', 'module' => 'Authentication & Profile'],
    'profile.update' => ['name' => 'Profile Update', 'module' => 'Authentication & Profile'],
    'dashboard.view' => ['name' => 'Dashboard View', 'module' => 'Dashboard & Analytics'],
    'analytics.view' => ['name' => 'Analytics View', 'module' => 'Dashboard & Analytics'],
    'schools.view' => ['name' => 'School View', 'module' => 'School Management'],
    'schools.create' => ['name' => 'School Create', 'module' => 'School Management'],
    'schools.update' => ['name' => 'School Update', 'module' => 'School Management'],
    'schools.delete' => ['name' => 'School Delete', 'module' => 'School Management'],
    'schools.export' => ['name' => 'School Export', 'module' => 'School Management'],
    'school_settings.view' => ['name' => 'School Settings View', 'module' => 'School Settings'],
    'school_settings.update' => ['name' => 'School Settings Update', 'module' => 'School Settings'],
    'users.view' => ['name' => 'User View', 'module' => 'User Management'],
    'users.create' => ['name' => 'User Create', 'module' => 'User Management'],
    'users.update' => ['name' => 'User Update', 'module' => 'User Management'],
    'users.delete' => ['name' => 'User Delete', 'module' => 'User Management'],
    'users.export' => ['name' => 'User Export', 'module' => 'User Management'],
    'roles.view' => ['name' => 'Role View', 'module' => 'Role & Permission'],
    'roles.assign' => ['name' => 'Role Assign', 'module' => 'Role & Permission'],
    'roles.manage' => ['name' => 'Role Manage', 'module' => 'Role & Permission'],
    'academic.view' => ['name' => 'Academic Structure View', 'module' => 'Academic Structure'],
    'academic.create' => ['name' => 'Academic Structure Create', 'module' => 'Academic Structure'],
    'academic.update' => ['name' => 'Academic Structure Update', 'module' => 'Academic Structure'],
    'academic.delete' => ['name' => 'Academic Structure Delete', 'module' => 'Academic Structure'],
    'academic.export' => ['name' => 'Academic Structure Export', 'module' => 'Academic Structure'],
    'students.view' => ['name' => 'Student View', 'module' => 'Student Management'],
    'students.create' => ['name' => 'Student Create', 'module' => 'Student Management'],
    'students.update' => ['name' => 'Student Update', 'module' => 'Student Management'],
    'students.delete' => ['name' => 'Student Delete', 'module' => 'Student Management'],
    'students.export' => ['name' => 'Student Export', 'module' => 'Student Management'],
    'attendance.view' => ['name' => 'Attendance View', 'module' => 'Attendance Management'],
    'attendance.create' => ['name' => 'Attendance Create', 'module' => 'Attendance Management'],
    'attendance.update' => ['name' => 'Attendance Update', 'module' => 'Attendance Management'],
    'attendance.delete' => ['name' => 'Attendance Delete', 'module' => 'Attendance Management'],
    'attendance.report' => ['name' => 'Attendance Report', 'module' => 'Attendance Management'],
    'attendance.export' => ['name' => 'Attendance Export', 'module' => 'Attendance Management'],
    'fees.view' => ['name' => 'Fee View', 'module' => 'Fee Management'],
    'fees.create' => ['name' => 'Fee Create', 'module' => 'Fee Management'],
    'fees.update' => ['name' => 'Fee Update', 'module' => 'Fee Management'],
    'fees.delete' => ['name' => 'Fee Delete', 'module' => 'Fee Management'],
    'fees.collect' => ['name' => 'Fee Collect', 'module' => 'Fee Management'],
    'fees.report' => ['name' => 'Fee Report', 'module' => 'Fee Management'],
    'fees.export' => ['name' => 'Fee Export', 'module' => 'Fee Management'],
    'exams.view' => ['name' => 'Examination View', 'module' => 'Examination Management'],
    'exams.create' => ['name' => 'Examination Create', 'module' => 'Examination Management'],
    'exams.update' => ['name' => 'Examination Update', 'module' => 'Examination Management'],
    'exams.delete' => ['name' => 'Examination Delete', 'module' => 'Examination Management'],
    'exams.publish' => ['name' => 'Examination Publish', 'module' => 'Examination Management'],
    'exams.report' => ['name' => 'Examination Report', 'module' => 'Examination Management'],
    'exams.export' => ['name' => 'Examination Export', 'module' => 'Examination Management'],
    'reports.view' => ['name' => 'Report View', 'module' => 'Reporting'],
    'reports.export' => ['name' => 'Report Export', 'module' => 'Reporting'],
    'activity_logs.view' => ['name' => 'Activity Log View', 'module' => 'Activity Logs'],
    'audit_logs.view' => ['name' => 'Audit Log View', 'module' => 'Audit Trail'],
    'backups.view' => ['name' => 'Backup View', 'module' => 'Backup Management'],
    'backups.create' => ['name' => 'Backup Create', 'module' => 'Backup Management'],
    'backups.download' => ['name' => 'Backup Download', 'module' => 'Backup Management'],
    'backups.delete' => ['name' => 'Backup Delete', 'module' => 'Backup Management'],
];

$maximumMappings = [
    'super_admin' => [
        'profile.view', 'profile.update', 'dashboard.view', 'analytics.view',
        'schools.view', 'schools.create', 'schools.update', 'schools.delete', 'schools.export',
        'school_settings.view',
        'users.view', 'users.create', 'users.update', 'users.delete', 'users.export',
        'roles.view', 'roles.assign', 'roles.manage',
        'academic.view', 'students.view',
        'attendance.report', 'fees.report', 'exams.report',
        'reports.view', 'reports.export',
        'activity_logs.view', 'audit_logs.view',
        'backups.view', 'backups.create', 'backups.download', 'backups.delete',
    ],
    'school_admin' => [
        'profile.view', 'profile.update', 'dashboard.view', 'analytics.view',
        'school_settings.view', 'school_settings.update',
        'users.view', 'users.create', 'users.update', 'users.delete', 'users.export',
        'roles.view', 'roles.assign',
        'academic.view', 'academic.create', 'academic.update', 'academic.delete', 'academic.export',
        'students.view', 'students.create', 'students.update', 'students.delete', 'students.export',
        'attendance.view', 'attendance.create', 'attendance.update', 'attendance.delete',
        'attendance.report', 'attendance.export',
        'fees.view', 'fees.create', 'fees.update', 'fees.delete', 'fees.collect', 'fees.report', 'fees.export',
        'exams.view', 'exams.create', 'exams.update', 'exams.delete', 'exams.publish', 'exams.report', 'exams.export',
        'reports.view', 'reports.export',
        'activity_logs.view', 'audit_logs.view',
    ],
    'teacher' => [
        'profile.view', 'profile.update', 'dashboard.view', 'analytics.view',
        'academic.view', 'students.view',
        'attendance.view', 'attendance.create', 'attendance.update', 'attendance.delete',
        'attendance.report', 'attendance.export',
        'exams.view', 'exams.create', 'exams.update', 'exams.delete', 'exams.publish', 'exams.report', 'exams.export',
        'reports.view', 'reports.export',
    ],
    'accountant' => [
        'profile.view', 'profile.update', 'dashboard.view', 'analytics.view',
        'students.view',
        'fees.view', 'fees.collect',
        'reports.view', 'reports.export',
    ],
];

return [
    'roles' => $roles,
    'permissions' => $permissions,
    'maximum_mappings' => $maximumMappings,
    'default_mappings' => $maximumMappings,
    'essential_permissions' => [
        'super_admin' => $maximumMappings['super_admin'],
        'school_admin' => [
            'profile.view', 'profile.update', 'dashboard.view',
            'users.view', 'users.update', 'roles.view', 'roles.assign',
        ],
        'teacher' => ['profile.view', 'profile.update', 'dashboard.view'],
        'accountant' => ['profile.view', 'profile.update', 'dashboard.view'],
    ],
    'bootstrap_super_admin' => [
        'name' => env('SUPER_ADMIN_NAME', 'Super Admin'),
        'email' => env('SUPER_ADMIN_EMAIL', 'superadmin@example.com'),
        'password' => env('SUPER_ADMIN_PASSWORD'),
    ],
];
