<x-app-layout>
    <x-slot name="header">
        <div class="d-flex flex-column flex-sm-row align-items-sm-center justify-content-between gap-3">
            <div>
                <h1 class="h3 mb-1">{{ __('Backup Details') }}</h1>
                <p class="text-body-secondary mb-0">{{ ucfirst($backupLog->backup_scope) }} {{ ucfirst($backupLog->backup_type) }} backup</p>
            </div>
            <div class="d-flex flex-wrap gap-2 align-self-start">
                @can('download', $backupLog)
                    <a class="btn btn-outline-primary" href="{{ route('backups.download', $backupLog) }}">
                        <i class="bi bi-download me-1" aria-hidden="true"></i>{{ __('Download Backup') }}
                    </a>
                @endcan
                @can('delete', $backupLog)
                    <button class="btn btn-outline-danger" type="button" data-bs-toggle="modal" data-bs-target="#deleteBackupModal">
                        <i class="bi bi-trash me-1" aria-hidden="true"></i>{{ __('Remove File') }}
                    </button>
                    <div class="modal fade" id="deleteBackupModal" tabindex="-1" aria-labelledby="deleteBackupModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h2 class="modal-title fs-5" id="deleteBackupModalLabel">{{ __('Remove Backup File') }}</h2>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="{{ __('Close') }}"></button>
                                </div>
                                <div class="modal-body">
                                    <p class="mb-0">{{ __('This removes the private backup file only. The backup history record will be retained with a deleted status.') }}</p>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">{{ __('Cancel') }}</button>
                                    <form method="POST" action="{{ route('backups.destroy', $backupLog) }}">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger">{{ __('Remove File') }}</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                @endcan
            </div>
        </div>
    </x-slot>

    @include('system-operations.partials.navigation')

    @if (session('status'))
        <div class="alert alert-success" role="status">{{ session('status') }}</div>
    @endif
    @if ($errors->has('backup'))
        <div class="alert alert-danger" role="alert">{{ $errors->first('backup') }}</div>
    @endif

    <div class="card border-0 shadow-sm mb-4">
        <div class="card-body">
            <dl class="row mb-0">
                <dt class="col-sm-3">{{ __('Status') }}</dt>
                <dd class="col-sm-9"><span class="badge text-bg-secondary">{{ ucfirst($backupLog->status) }}</span></dd>

                <dt class="col-sm-3">{{ __('Scope') }}</dt>
                <dd class="col-sm-9">{{ ucfirst($backupLog->backup_scope) }}</dd>

                <dt class="col-sm-3">{{ __('Type') }}</dt>
                <dd class="col-sm-9">{{ ucfirst($backupLog->backup_type) }}</dd>

                <dt class="col-sm-3">{{ __('Started At') }}</dt>
                <dd class="col-sm-9">{{ $backupLog->started_at?->format('Y-m-d H:i:s') ?? '—' }}</dd>

                <dt class="col-sm-3">{{ __('Completed At') }}</dt>
                <dd class="col-sm-9">{{ $backupLog->completed_at?->format('Y-m-d H:i:s') ?? '—' }}</dd>

                <dt class="col-sm-3">{{ __('Generated By') }}</dt>
                <dd class="col-sm-9">{{ $backupLog->generatedBy?->name ?? __('System') }}</dd>

                <dt class="col-sm-3">{{ __('File Size') }}</dt>
                <dd class="col-sm-9">
                    @if ($backupLog->file_size_bytes)
                        {{ number_format($backupLog->file_size_bytes / 1024, 1) }} KB
                    @else
                        —
                    @endif
                </dd>

                @if ($backupLog->error_message)
                    <dt class="col-sm-3">{{ __('Error') }}</dt>
                    <dd class="col-sm-9 text-danger">{{ $backupLog->error_message }}</dd>
                @endif
            </dl>
        </div>
    </div>

    <a class="btn btn-link px-0" href="{{ route('backups.index') }}">{{ __('Back to backup history') }}</a>
</x-app-layout>
